name             'apache'
maintainer       'Paul Mattioli'
maintainer_email 'mattioli.paul@gmail.com'
license          'MIT'
description      'Installs/Configures apache'
long_description 'Installs/Configures apache'
version          '0.1.0'
